spring:
  datasource:
    url: ...
    username: ...
    password: ...

  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  token:
    secret: secret_key
    expired: 360000000

bank:
  name: bank1
  key_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFuazEiLCJjb3VudHJ5IjoiUnVzc2lhIiwiaWQiOjMyMjh9.KvcgfR4jpcDmCGuYtm0MgkvnzRhX80oEtVmKvAc9HXk

central_bank:
  url: http://localhost:8081
